#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/mileszs/ack.vim.git",
  "git://github.com/tpope/vim-fugitive",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-speeddating",
  "git://github.com/chrismetcalf/vim-yankring.git",
  "git://github.com/chrismetcalf/vim-taglist.git",

  "git://github.com/codegram/vim-todo.git",
  "git://github.com/codegram/vim-numberlock.git",

  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/rstacruz/sparkup.git",

  "git://github.com/panozzaj/vim-autocorrect.git",

  "git://github.com/tsaleh/vim-tcomment.git"

  # "git://github.com/msanders/snipmate.vim.git"  Oriol does not like it
]

vim_org_scripts = [
  ["gist","13427", "plugin"],
  ["LustyJuggler","13094", "plugin"]
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
